version: '3.9'

services:
  db:
    image: postgres:latest

    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5431:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data


