# Generated by Django 4.0.6 on 2022-10-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mainparameters_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество в наличии'),
        ),
    ]
