# Generated by Django 4.0.6 on 2022-10-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sales_company_alter_supplierproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='activate_sales',
            field=models.BooleanField(default=False, verbose_name='Активировать получение заказов'),
        ),
    ]
