# Generated by Django 4.0.6 on 2023-01-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sales_activate_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение e-mail'),
        ),
    ]
